[package]
name = "rust-app"
version = "0.1.0"
authors = ["Timur Samkharadze <timur.samkharadze@sysco.no>"]
edition = "2018"

[dependencies]
node2object = "0.1.2"
treexml = "0.6.2"
serde_json = "1.0.39"
exitcode = "1.1.2"